# Generated by Django 2.0.7 on 2018-07-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=None, help_text='开始时间')),
                ('end', models.DateTimeField(default=None, help_text='结束时间')),
                ('state', models.CharField(default='未开始', help_text='状态', max_length=32)),
            ],
        ),
    ]
