# Generated by Django 2.0.7 on 2018-07-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='dif',
            field=models.DateTimeField(default=None, help_text='时间差'),
        ),
    ]
