# Generated by Django 2.0.7 on 2018-07-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timing', '0002_meeting_dif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='dif',
            field=models.DateTimeField(default=None, help_text='时间差', null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='end',
            field=models.DateTimeField(default=None, help_text='结束时间', null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start',
            field=models.DateTimeField(default=None, help_text='开始时间', null=True),
        ),
    ]
