# Generated by Django 2.0.7 on 2018-07-06 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timing', '0003_auto_20180705_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='dif',
        ),
    ]
