# Generated by Django 2.0.7 on 2018-07-06 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookLibrary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(help_text='作者', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookLibrary.Author'),
        ),
    ]
